server:
  tomcat:
    max-http-form-post-size: 5MB
    uri-encoding: UTF-8

spring:
  profiles:
    active: local
  datasource:
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
#    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      connection-timeout: 30000
      maximum-pool-size: 3
      max-lifetime: 58000
      pool-name: Hikari
      read-only: false
  jpa:
    hibernate:
      ddl-auto: none
    database: mysql
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    show-sql: true
    properties:
      hibernate:
        format_sql: true
#    properties:
#    defer-datasource-initialization: true
#          generate-ddl: false
#          hibernate:
#            ddl-auto: none

log4jdbc:
  spylogdelegator:
    name: net.sf.log4jdbc.log.slf4j.Slf4jSpyLogDelegator

logging:
  level:
    root: debug
#      org: debug
    org:
      hibernate:
        type:
          descriptor:
            sql: trace
---

spring:
  config:
    activate:
      on-profile: local
  datasource:
    url: jdbc:log4jdbc:mysql://localhost:3306/springframework?characterEncoding=UTF-8&serverTimezone=UTC
#    url: jdbc:mysql://localhost:3306/springframework?characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: as!234
#    url: jdbc:log4jdbc:h2:mem:local;MODE=ORACLE
#    username: sa
#    password:
#  h2:
#    console:
#      enabled: true
#      path: /h2
#  jackson:
#    serialization:
#      FAIL_ON_EMPTY_BEANS: false
server:
  port: 9001

---
spring:
  config:
    activate:
      on-profile: dev


---
spring:
  config:
    activate:
      on-profile: prod