server:
  tomcat:
    max-http-form-post-size: 5MB
    uri-encoding: UTF-8
  port: 8080

spring:
  profiles:
    active: local
  datasource:
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    hikari:
      connection-timeout: 30000
      maximum-pool-size: 3
      max-lifetime: 58000
      pool-name: Hikari
      read-only: false
  jpa:
    defer-datasource-initialization: true

logging:
  level:
    root: debug
---

spring:
  config:
    activate:
      on-profile: local
  datasource:
    url: jdbc:log4jdbc:h2:mem:honghong
    username: sa
    password:
  h2:
    console:
      enabled: true
      path: /h2